#! flask/bin/python

from app import app, db
from app.models import *
from parse_challonge_run import *

parse_challonge_pool("http://challonge.com/mayhemJan24Pool8", "Mayhem 1-24-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJan24Pool7", "Mayhem 1-24-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJan24Pool6", "Mayhem 1-24-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJan24Pool5", "Mayhem 1-24-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJan24Pool4", "Mayhem 1-24-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJan24Pool3", "Mayhem 1-24-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJan24Pool2", "Mayhem 1-24-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJan24Pool1", "Mayhem 1-24-15", "SoCal", 4)

parse_challonge_pool("http://challonge.com/mayhemFeb28Pool8", "Mayhem 2-28-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemFeb28Pool7", "Mayhem 2-28-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemFeb28Pool6", "Mayhem 2-28-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemFeb28Pool5", "Mayhem 2-28-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemFeb28Pool4", "Mayhem 2-28-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemFeb28Pool3", "Mayhem 2-28-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemFeb28Pool2", "Mayhem 2-28-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemFeb28Pool1", "Mayhem 2-28-15", "SoCal", 4)

parse_challonge_pool("http://challonge.com/mayhemMar14Pool8", "Mayhem 3-14-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMar14Pool7", "Mayhem 3-14-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMar14Pool6", "Mayhem 3-14-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMar14Pool5", "Mayhem 3-14-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMar14Pool4", "Mayhem 3-14-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMar14Pool3", "Mayhem 3-14-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMar14Pool2", "Mayhem 3-14-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMar14Pool1", "Mayhem 3-14-15", "SoCal", 4)

parse_challonge_pool("http://challonge.com/mayhemApr4Pool8", "Mayhem 4-4-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemApr4Pool7", "Mayhem 4-4-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemApr4Pool6", "Mayhem 4-4-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemApr4Pool5", "Mayhem 4-4-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemApr4Pool4", "Mayhem 4-4-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemApr4Pool3", "Mayhem 4-4-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemApr4Pool2", "Mayhem 4-4-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemApr4Pool1", "Mayhem 4-4-15", "SoCal", 4)

parse_challonge_pool("http://challonge.com/mayhemMay2Pool8", "Mayhem 5-2-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMay2Pool7", "Mayhem 5-2-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMay2Pool6", "Mayhem 5-2-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMay2Pool5", "Mayhem 5-2-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMay2Pool4", "Mayhem 5-2-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMay2Pool3", "Mayhem 5-2-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMay2Pool2", "Mayhem 5-2-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemMay2Pool1", "Mayhem 5-2-15", "SoCal", 4)

parse_challonge_pool("http://challonge.com/mayhemJune6pool8", "Mayhem 6-6-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJune6pool7", "Mayhem 6-6-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJune6pool6", "Mayhem 6-6-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJune6pool5", "Mayhem 6-6-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJune6pool4", "Mayhem 6-6-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJune6pool3", "Mayhem 6-6-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJune6pool2", "Mayhem 6-6-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJune6pool1", "Mayhem 6-6-15", "SoCal", 4)

parse_challonge_pool("http://challonge.com/mayhemJuly11Pool8", "Mayhem 7-11-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJuly11Pool7", "Mayhem 7-11-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJuly11Pool6", "Mayhem 7-11-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJuly11Pool5", "Mayhem 7-11-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJuly11Pool4", "Mayhem 7-11-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJuly11Pool3", "Mayhem 7-11-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJuly11Pool2", "Mayhem 7-11-15", "SoCal", 4)
parse_challonge_pool("http://challonge.com/mayhemJuly11Pool1", "Mayhem 7-11-15", "SoCal", 4)

parse_challonge_pool("http://challonge.com/HUSHPool1", "HUSH", "New England", 2))
parse_challonge_pool("http://challonge.com/HUSHPool2", "HUSH", "New England", 2))
parse_challonge_pool("http://challonge.com/HUSHPool3", "HUSH", "New England", 2))
parse_challonge_pool("http://challonge.com/HUSHPool4", "HUSH", "New England", 2))
